//login
export const CHECKLIST_SET_LOGIN_INIT = "CHECKLIST_SET_LOGIN_INIT";
export const CHECKLIST_SET_LOGIN_SUCCESS = "CHECKLIST_SET_LOGIN_SUCCESS"; 
export const CHECKLIST_SET_LOGIN_FAIL = "CHECKLIST_SET_LOGIN_FAIL"; 

export const ASSET_SET_LOGIN_INIT = "ASSET_SET_LOGIN_INIT";
export const ASSET_SET_LOGIN_SUCCESS = "ASSET_SET_LOGIN_SUCCESS"; 
export const ASSET_SET_LOGIN_FAIL = "ASSET_SET_LOGIN_FAIL"; 

//logout
export const SET_LOGOUT = "SET_LOGOUT"; 

//user
export const SET_USER_STATE = "SET_USER_STATE";
export const SET_USER_SUCCESS = "SET_USER_SUCCESS";
export const SET_USER_FAIL = "SET_USER_FAIL";

//users
export const SET_ENT_USERS_STATE = "SET_ENT_USERS_STATE";
export const SET_ENT_USERS_SUCCESS = "SET_ENT_USERS_SUCCESS";
export const SET_ENT_USERS_FAIL = "SET_ENT_USERS_FAIL";

//ent_khoicv
export const SET_ENT_KHOICV_STATE = "SET_ENT_KHOICV_STATE";
export const SET_ENT_KHOICV_SUCCESS = "SET_ENT_KHOICV_SUCCESS";
export const SET_ENT_KHOICV_FAIL = "SET_ENT_KHOICV_FAIL";

//ent_calv
export const SET_ENT_CALV_STATE = "SET_ENT_CALV_STATE";
export const SET_ENT_CALV_SUCCESS = "SET_ENT_CALV_SUCCESS";
export const SET_ENT_CALV_FAIL = "SET_ENT_CALV_FAIL";

//ent_giamsat
export const SET_ENT_GIAMSAT_STATE = "SET_ENT_GIAMSAT_STATE";
export const SET_ENT_GIAMSAT_SUCCESS = "SET_ENT_GIAMSAT_SUCCESS";
export const SET_ENT_GIAMSAT_FAIL = "SET_ENT_GIAMSAT_FAIL";

//ent_toanha
export const SET_ENT_TOANHA_STATE = "SET_ENT_TOANHA_STATE";
export const SET_ENT_TOANHA_SUCCESS = "SET_ENT_TOANHA_SUCCESS";
export const SET_ENT_TOANHA_FAIL = "SET_ENT_TOANHA_FAIL";

//ent_khuvuc
export const SET_ENT_KHUVUC_STATE = "SET_ENT_KHUVUC_STATE";
export const SET_ENT_KHUVUC_SUCCESS = "SET_ENT_KHUVUC_SUCCESS";
export const SET_ENT_KHUVUC_FAIL = "SET_ENT_KHUVUC_FAIL";

//ent_duan
export const SET_ENT_DUAN_STATE = "SET_ENT_DUAN_STATE";
export const SET_ENT_DUAN_SUCCESS = "SET_ENT_DUAN_SUCCESS";
export const SET_ENT_DUAN_FAIL = "SET_ENT_DUAN_FAIL";

//ent_chucvu
export const SET_ENT_CHUCVU_STATE = "SET_ENT_CHUCVU_STATE";
export const SET_ENT_CHUCVU_SUCCESS = "SET_ENT_CHUCVU_SUCCESS";
export const SET_ENT_CHUCVU_FAIL = "SET_ENT_CHUCVU_FAIL";

//ent_checklist
export const SET_ENT_CHECKLIST_STATE = "SET_ENT_CHECKLIST_STATE";
export const SET_ENT_CHECKLIST_SUCCESS = "SET_ENT_CHECKLIST_SUCCESS";
export const SET_ENT_CHECKLIST_FAIL = "SET_ENT_CHECKLIST_FAIL";

//ent_hangmuc
export const SET_ENT_HANGMUC_STATE = "SET_ENT_HANGMUC_STATE";
export const SET_ENT_HANGMUC_SUCCESS = "SET_ENT_HANGMUC_SUCCESS";
export const SET_ENT_HANGMUC_FAIL = "SET_ENT_HANGMUC_FAIL";

//ent_checklist_detail
export const SET_ENT_CHECKLIST_DETAIL_STATE = "SET_ENT_CHECKLIST_DETAIL_STATE";
export const SET_ENT_CHECKLIST_DETAIL_SUCCESS = "SET_ENT_CHECKLIST_DETAIL_SUCCESS";
export const SET_ENT_CHECKLIST_DETAIL_FAIL = "SET_ENT_CHECKLIST_DETAIL_FAIL";

//tb_checklistc
export const SET_TB_CHECKLISTC_STATE = "SET_TB_CHECKLISTC_STATE";
export const SET_TB_CHECKLISTC_SUCCESS = "SET_TB_CHECKLISTC_SUCCESS";
export const SET_TB_CHECKLISTC_FAIL = "SET_TB_CHECKLISTC_FAIL";

//ent_tang
export const SET_ENT_TANG_STATE = "SET_ENT_TANG_STATE";
export const SET_ENT_TANG_SUCCESS = "SET_ENT_TANG_SUCCESS";
export const SET_ENT_TANG_FAIL = "SET_ENT_TANG_FAIL";
